server:
  port: ${PORT:8000}
spring:
  application:
    name: api-client
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      # 將服務註冊到eureka-server
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false
    statusPageUrlPath: ${management.server.servlet.context-path}/info
    healthCheckUrlPath: ${management.server.servlet.context-path}/health
  #   metadata-map:
  #     management:
  #       context-path: ${management.server.servlet.context-path}
management:
  server:
    port: ${PORT:8000}
    servlet:
      context-path: /custom
  endpoints:
    jmx:
      exposure:
        include: *
message: dev mode change