server:
  port: ${PORT:${SERVER_PORT:0}}
  #  這個的意思是隨機指定個沒使用的埠
info:
  id: ${spring.application.name}
debug: true
spring:
  sleuth:
    log:
      json:
        enabled: true
  cloud:
    bus:
        enabled: true
        trace:
          enabled: true
    rabbitmq:
      host: localhost
      port: 15672
      username: guest
      password: guest
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wex"
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh