server:
  port: ${PORT:8002}
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      # 將服務註冊到eureka-server
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    config:
      discovery:
        enabled: true
      serviceId: user-service
foo: foo version 4